### PR TITLE
Cargo package only the required stuff

### PR DESCRIPTION
**Pull request by est31**
The .crate file before this PR:
```
$ du target/package/divans-0.0.1.crate 
1664    target/package/divans-0.0.1.crate
```
The .crate file after this PR:
```
$ du target/package/divans-0.0.1.crate 
1468    target/package/divans-0.0.1.crate
```

### CODE REVIEW

**Comment by est31** [comment]
Hopefully this reduction is appreciated, given the nature of this crate :).

**Comment by est31** [comment]
I'm not entirely sure whether to include the `testdata/` directory or not. On one hand, it would give helpful information to [crater](https://github.com/rust-lang-nursery/crater) which runs `cargo test` on the `.crate` file. On the other hand, that's the only use case, otherwise it increase size for everyone. I've excluded it as crater also tests `cargo build` which should work after the commit as well, it just won't report regressions in `cargo test`.

**Comment by danielrh** [comment]
We have had a regression in cargo test once before--with some of the wilder command line flags... I think we may need to keep those files in :-/ maybe we can make a divans-nostdlib subcrate be smaller?

being included in crater is pretty important

**Comment by est31** [comment]
Adjusted it. Still a 10% reduction :)

**Comment by est31** [comment]
@danielrh want to review this PR?

**Comment by est31** [comment]
Friendly ping @danielrh

**Comment by est31** [comment]
Seems this repo is dead. Closing.

**Pull request closed without merging**
